#' CAnutrients
#' A data package for CAnutrients.
#' @docType package
#' @aliases CAnutrients-package
#' @title Tidied Canadian Nutrient File 2015 Datasets
#' @name CAnutrients
#' @description All eleven datasets from the Canadian Nutrient File (CNF) 2015
#'   edition, tidied for correct data types and removal of extraneous columns.
#' @details Use \code{data(package='CAnutrients')$results[, 3]} to see a list of
#'   available data sets in this data package and/or DataPackageR::load_all
#'   _datasets() to load them.
#' @seealso \link{ca_conversion_factor}, \link{ca_food_group}, \link{ca_food_name},
#'   \link{ca_food_source}, \link{ca_measure_name}, \link{ca_nutrient_amount},
#'   \link{ca_nutrient_name}, \link{ca_nutrient_source}, \link{ca_refuse_amount},
#'   \link{ca_refuse_name}, \link{ca_yield_amount}, \link{ca_yield_name}
NULL




#' This dataset contains portion size conversion factors. The conversion factors
#' are food specific multipliers by which the nutrient values for each food may
#' be multiplied to give the nutrients in described portions.
#' @name ca_conversion_factor
#' @docType data
#' @title Conversion factor dataset
#' @format a \code{tbl_df} with 19,505 observations of the following
#'   4 fields:
#' \describe{
#' \item{FoodID}{Sequential number generated by the database identifying the
#' food records. Joins with \link{ca_food_name}.}
#' \item{MeasureID}{Sequential number generated by the database for the measure
#' descriptions. Joins with \link{ca_measure_name}.}
#' \item{ConversionFactorValue}{The factor by which one would multiply the
#' nutrient per 100g to obtain nutrient amounts per the measure described (the
#' weight of that food in the measure described divided by 100).}
#' \item{ConvFactorDateOfEntry}{	Date the data was entered into the database.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples 
#' ca_conversion_factor
#' 
#' if(require("dplyr")){
#' head(ca_conversion_factor, 20) %>%
#' left_join(ca_measure_name) %>%
#' left_join(ca_food_name) %>%
#' select(FoodDescription, ConversionFactorValue, MeasureDescription)
#' }
#' 
#' @seealso
#' \link{CAnutrients}
#' \link{ca_food_group}
#' \link{ca_food_name}
#' \link{ca_food_source}
#' \link{ca_measure_name}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_name}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_amount}
#' \link{ca_refuse_name}
#' \link{ca_yield_amount}
#' \link{ca_yield_name}
NULL




#' This dataset is a support or "list" table that is used to link to the
#' \link{ca_food_name} table. It contains a list of 23 different group headings
#' (in English and French) based on similar characteristics of the foods.
#' @name ca_food_group
#' @docType data
#' @title Food group dataset
#' @format a \code{tbl_df} with 23 observations of the following 4 fields:
#' \describe{
#' \item{FoodGroupID}{Sequential number generated by the database for the food
#' groups. Joins with \link{ca_food_name}.}
#' \item{FoodGroupCode}{Identifier code for the Canadian Nutrient File food
#' groups. There are 23 different CNF food groups.}
#' \item{FoodGroupName}{Food group name in English. }
#' \item{FoodGroupNameF}{Food group name in French.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples 
#' ca_food_group
#' 
#' if (require("dplyr")){
#' head(ca_food_name, 20) %>% 
#' left_join(ca_food_group) %>%
#' select(FoodDescription, FoodGroupName)
#' }
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_name}
#' \link{ca_food_source}
#' \link{ca_measure_name}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_name}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_amount}
#' \link{ca_refuse_name}
#' \link{ca_yield_amount}
#' \link{ca_yield_name}
NULL




#' This dataset stores information about each food in the database. It contains
#' a description of each food in English and French as well as dates and
#' comments.
#' @name ca_food_name
#' @docType data
#' @title Food name dataset
#' @format a \code{tbl_df} with 5,690 observations of the 10 following fields:
#' \describe{
#' \item{FoodID}{Sequential number generated by the database identifying the
#' food records.  This is the primary key. Joins with \link{ca_nutrient_amount},
#' \link{ca_conversion_factor}, \link{ca_yield_amount}, and
#' \link{ca_refuse_amount}.}
#' \item{FoodCode}{	Identifier code for the foods.  In the 2007b version this
#' was the FD_C. }
#' \item{FoodGroupID}{Sequential number generated by the database for the food
#' groups. Joins with \link{ca_food_group}.}
#' \item{FoodSourceID}{Sequential number generated by the database for the food
#' sources. Joins with \link{ca_food_source}.}
#' \item{FoodDescription}{Complete food name in English.}
#' \item{FoodDescriptionF}{Complete food name in French.}
#' \item{FoodDateOfEntry}{Date the food name data was entered into the database}
#' \item{FoodDateOfPublication}{Date the food name data was entered into the
#' database.}
#' \item{CountryCode}{Corresponds to the USDA NDB code.}
#' \item{ScientificName}{Scientific name of the food.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples
#' ca_food_name
#' 
#' if (require("dplyr")){ 
#' head(ca_food_name, 20) %>% 
#' left_join(ca_food_group) %>%
#' select(FoodDescription, FoodGroupName)
#' }
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_group}
#' \link{ca_food_source}
#' \link{ca_measure_name}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_name}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_amount}
#' \link{ca_refuse_name}
#' \link{ca_yield_amount}
#' \link{ca_yield_name}
NULL




#' This dataset is a support or "list" table that is used to link to the
#' \link{ca_food_name} table. It contains a list of several food sources (in
#' English and French) that foods can be grouped on.
#' @name ca_food_source
#' @docType data
#' @title Food source dataset
#' @format a \code{tbl_df} with 16 observations of the following 4 fields:
#' \describe{
#' \item{FoodSourceID}{	Sequential number generated by the database for the food
#' sources. Joins with \link{ca_food_name}.}
#' \item{FoodSourceCode}{Identifier code for the food sources. Food sources give
#' an indication as to Canadian content.}
#' \item{FoodSourceDescription}{Food Source description in English}
#' \item{FoodSourceDescriptionF}{Food Source description in French}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples 
#' ca_food_source
#' 
#' if (require("dplyr"){
#' head(ca_food_name, 20) %>% 
#' left_join(food_source) %>%
#' select(FoodDescription, FoodSourceDescription)
#' }
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_group}
#' \link{ca_food_name}
#' \link{ca_measure_name}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_name}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_amount}
#' \link{ca_refuse_name}
#' \link{ca_yield_amount}
#' \link{ca_yield_name}
NULL




#' This dataset is a support or "list" table that is used to link to the
#' \link{ca_conversion_factor} table. It contains a list of measures (in English
#' and French).
#' @name ca_measure_name
#' @docType data
#' @title Measure name dataset
#' @format a \code{tbl_df} with 1,162 observations of the following 3 fields:
#' \describe{
#' \item{MeasureID}{Sequential number generated by the database for the measure
#' descriptions. Joins with \link{ca_conversion_factor}.}
#' \item{MeasureDescription}{Measure description in English.}
#' \item{MeasureDescriptionF}{Measure description in French.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples 
#' ca_measure_name
#' 
#' if (require("dplyr")){
#' head(ca_food_name) %>% 
#' left_join(ca_conversion_factor) %>%
#' left_join(ca_measure_name) %>% 
#' select(FoodDescription, MeasureDescription)
#' }
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_group}
#' \link{ca_food_name}
#' \link{ca_food_source}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_name}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_amount}
#' \link{ca_refuse_name}
#' \link{ca_yield_amount}
#' \link{ca_yield_name}
NULL




#' This is the main dataset. It uses information (by linking) from the
#' \link{ca_food_name} table (among others) to identify which nutrients and
#' amounts are recorded for that food.
#' @name ca_nutrient_amount
#' @docType data
#' @title Nutrient amount dataset
#' @format a \code{tbl_df} with 524,674 observations of the following 7 fields:
#' \describe{
#' \item{FoodID}{Sequential number generated by the database identifying the
#' food records. Joins with \link{ca_food_name}.}
#' \item{NutrientID}{Sequential number generated by the database for the
#' nutrient names. Joins with \link{ca_nutrient_name}.}
#' \item{NutrientValue}{Mean value in 100g, edible portion. (The number of
#' decimal places does not reflect the accuracy of the data.)}
#' \item{StandardError}{Standard error of the mean.}
#' \item{NumberofObservations}{Number of samples.}
#' \item{NutrientSourceID}{Identifier code generated by the database for the
#' nutrient source. Joins with \link{ca_nutrient_source}.}
#' \item{NutrientDateOfEntry}{Date the data was entered into the database.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples 
#' ca_nutrient_amount
#' 
#' if (require("dplyr")){
#' head(ca_food_name) %>%
#' left_join(ca_nutrient_amount) %>%
#' left_join(ca_nutrient_name) %>% 
#' select(FoodDescription, NutrientName, NutrientValue)
#' }
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_group}
#' \link{ca_food_name}
#' \link{ca_food_source}
#' \link{ca_measure_name}
#' \link{ca_nutrient_name}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_amount}
#' \link{ca_refuse_name}
#' \link{ca_yield_amount}
#' \link{ca_yield_name}
NULL




#' This dataset is a support or "list" table that contains the list of nutrients
#' (in English and French) used in the \link{ca_nutrient_amount} table, with
#' which it is linked.
#' @name ca_nutrient_name
#' @docType data
#' @title Nutrient name dataset
#' @format a \code{tbl_df} with 152 observations of the following 8 fields:
#' \describe{
#' \item{NutrientID}{Sequential number generated by the database for the
#' nutrient names. Joins with \link{ca_nutrient_amount}.}
#' \item{NutrientCode}{Identifier code for nutrient name descriptions.}
#' \item{NutrientSymbol}{Nutrient symbol or abbreviation of the nutrients. They
#' may differ from international nomenclature.}
#' \item{NutrientUnit}{Unit of measure (e.g., mg, g, mcg)}
#' \item{NutrientName}{Nutrient name in English}
#' \item{NutrientNameF}{Nutrient name in French}
#' \item{Tagname}{International Network of Food Data Systems (INFOODS) Tagnames.
#' A unique Abbreviation for a food component developed by INFOODS to aid in the
#' interchange of data.}
#' \item{NutrientDecimals}{	Number of decimal places used in the rounding of the
#' nutrient value.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples
#' ca_nutrient_name
#' 
#' if (require("dplyr")){
#' head(ca_food_name) %>%
#' left_join(ca_nutrient_amount) %>%
#' left_join(ca_nutrient_name) %>% 
#' select(FoodDescription, NutrientName, NutrientValue)
#' }
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_group}
#' \link{ca_food_name}
#' \link{ca_food_source}
#' \link{ca_measure_name}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_amount}
#' \link{ca_refuse_name}
#' \link{ca_yield_amount}
#' \link{ca_yield_name}
NULL




#' This dataset is a support or "list" table that is used to link to the
#' \link{ca_nutrient_amount} file. It contains a list of several sources and/or
#' types of nutrient data (in English and French).
#' @name ca_nutrient_source
#' @docType data
#' @title Nutrient source dataset
#' @format a \code{tbl_df} with 20 observations of the following 4 fields:
#' \describe{
#' \item{NutrientSourceID}{	Sequential number generated by the database for the
#' nutrient sources. Joins with \link{ca_nutrient_amount}.}
#' \item{NutrientSourceCode}{Identifier code for nutrient source descriptions.}
#' \item{NutrientSourceDescription}{Nutrient source description in English.}
#' \item{NutrientSourc.DescriptionF}{Nutrient source description in French.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples
#' ca_nutrient_source
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_group}
#' \link{ca_food_name}
#' \link{ca_food_source}
#' \link{ca_measure_name}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_name}
#' \link{ca_refuse_amount}
#' \link{ca_refuse_name}
#' \link{ca_yield_amount}
#' \link{ca_yield_name}
NULL




#' This dataset contains the percent of refuse, or inedible portion, for each food.
#' @name ca_refuse_amount
#' @docType data
#' @title Refuse amount dataset
#' @format a \code{tbl_df} with 6,897 observations of the following 4 fields:
#' \describe{
#' \item{FoodID}{Sequential number generated by the database identifying the
#' food records. Joins with \link{ca_food_name}.}
#' \item{RefuseID}{	Sequential number generated by the database for the refuse
#' descriptions. Joins with \link{ca_refuse_name}.}
#' \item{RefuseAmount}{Percent refuse}
#' \item{RefuseDateOfEntry}{Date the data was entered into the database.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples 
#' ca_refuse_amount
#' 
#' if(require("dplyr")){
#' ca_refuse_amount %>% 
#' left_join(ca_food_name) %>%
#' filter(RefuseAmount > 0) %>%
#' left_join(ca_refuse_name) %>%
#' filter(RefuseDescription != "total refuse") %>%
#' select(FoodDescription, RefuseDescription)
#' }
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_group}
#' \link{ca_food_name}
#' \link{ca_food_source}
#' \link{ca_measure_name}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_name}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_name}
#' \link{ca_yield_amount}
#' \link{ca_yield_name}
NULL




#' This dataset is a support or "list" table that is used to link to the
#' \link{ca_refuse_amount} table. It contains a list of refuse types.
#' @name ca_refuse_name
#' @docType data
#' @title Refuse name dataset
#' @format a \code{tbl_df} with 1,047,335 observations of the following 3 fields:
#' \describe{
#' \item{RefuseID}{Sequential number generated by the database for the refuse
#' descriptions. Joins with \link{ca_refuse_amount}.}
#' \item{RefuseDescription}{Refuse description in English.}
#' \item{RefuseDescriptionF}{Refuse description in French.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples 
#' ca_refuse_name
#' 
#' if(require("dplyr")){
#'   head(ca_refuse_name) %>% 
#'     left_join(ca_refuse_amount) %>%
#'     filter(RefuseDescription != "total refuse") %>%
#'     left_join(ca_food_name) %>%
#'     select(FoodDescription, RefuseDescription)
#' }
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_group}
#' \link{ca_food_name}
#' \link{ca_food_source}
#' \link{ca_measure_name}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_name}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_amount}
#' \link{ca_yield_amount}
#' \link{ca_yield_name}
NULL




#' This dataset contains the yield from refuse and/or cooking losses assigned to
#' certain foods. These yields are most often used for food inventory purposes.
#' @name ca_yield_amount
#' @docType data
#' @title Yield amount dataset
#' @format a \code{tbl_df} with 1,426 observations of the following 4 fields:
#' \describe{
#' \item{FoodID}{Sequential number generated by the database identifying the
#' food records. Joins with \link{ca_food_name}.}
#' \item{YieldID}{Sequential number generated by the database for the yield
#' descriptions. Joins with \link{ca_yield_name}.}
#' \item{YieldAmount}{Yield from refuse and/or cooking losses.}
#' \item{YieldDateofEntry}{Date the data was entered into the database.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples 
#' ca_yield_amount
#' 
#' if (require("dplyr")){
#'   head(ca_yield_amount) %>% 
#'     left_join(ca_yield_name) %>%
#'     left_join(ca_food_name) %>%
#'     select(FoodDescription, YieldDescription, YieldAmount)
#' }
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_group}
#' \link{ca_food_name}
#' \link{ca_food_source}
#' \link{ca_measure_name}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_name}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_amount}
#' \link{ca_refuse_name}
#' \link{ca_yield_name}
NULL




#' This dataset is a support or "list" table that is used to link to the yield
#' table. It contains a list of yield types or yield descriptions (in English
#' and French).
#' @name ca_yield_name
#' @docType data
#' @title Yield name dataset
#' @format a \code{tbl_df} with 1,047,266 observations of the following 3 fields:
#' \describe{
#' \item{YieldID}{Sequential number generated by the database for the yield
#' descriptions. Joins with \link{ca_yield_amount}.}
#' \item{YieldDescription}{Yield description in English.}
#' \item{YieldDescriptionF}{Yield description in French.}
#' }
#' @source The data comes from Canadian Nutrient File 2015.
#' @examples 
#' ca_yield_name
#' 
#' if (require("dplyr")){
#'   head(ca_yield_name) %>% 
#'     left_join(ca_yield_amount) %>%
#'     left_join(ca_food_name) %>%
#'     select(FoodDescription, YieldDescription, YieldAmount)
#' }
#' @seealso
#' \link{CAnutrients}
#' \link{ca_conversion_factor}
#' \link{ca_food_group}
#' \link{ca_food_name}
#' \link{ca_food_source}
#' \link{ca_measure_name}
#' \link{ca_nutrient_amount}
#' \link{ca_nutrient_name}
#' \link{ca_nutrient_source}
#' \link{ca_refuse_amount}
#' \link{ca_refuse_name}
#' \link{ca_yield_amount}
NULL
